# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceaf328d69651f07db6c50cd3540a8128260dd1c6741dd2690c7c3ee6168f7f53ac4027a0290b828956be865b94e50ebdbb87f550e39e6ca57d2fc0db297291d

test:
  secret_key_base: 44fb2eb12fc41ffdf25f512278e0e82eafc34b46af23b67b4c65f1c17d87763658e7da41be7627d39f4ee115addfb0e4920cafa057517b5b68af563a4cb09799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
